#ifndef DALI_ARRAY_OP_SPATIAL_ENUMS_H
#define DALI_ARRAY_OP_SPATIAL_ENUMS_H

enum PADDING_T {
    PADDING_T_SAME  = 0,
    PADDING_T_VALID = 1
};

enum POOLING_T {
    POOLING_T_MAX = 0,
    POOLING_T_AVG = 1,
};

#endif  // DALI_ARRAY_OP_SPATIAL_ENUMS_H
